### ISSUE TITLE
minified version for ChatGPT

### ISSUE THREAD

**Issue by darvin** [rodrigorc/raze#2]
Hi!

im trying to make ChatGPT to play ZX spectrum games. could you please make .min.js version to help accomplish that?

**Comment by rodrigorc** [comment]
Sorry, I'm not sure I understand your request. What do you mean with making a ".min.js" version? As far as I know a ".min.js" is just like a regular ".js" file but that has been minified to make it shorter and faster to load.

My ZX Spectrum emulator has a quite small ".js" file, I don't see the need to minimize it, and I don't see how ChatGPT could benefit from that. Moreover, the main emulator functionality is not in the JS but in a WASM file, where the minifying does not apply.

Now, given the nature of the request, I have to ask... @darvin, are you human or AI?

**Comment by darvin** [comment]
@rodrigorc  im human! :) 

I tried to import your wonderful emulator from generated page (without hosting it myself), it doesn't seem to be possible - as far as I understand it also needs .wasm file from your site. Is it possible somehow to include WASM into .min.js?...

I want to integrate it into this app:

http://github.com/STCData/Hypno

I guess the issue is not minifying per se but on the fly including without hosting .js / .wasm files, including from generated page

**Comment by rodrigorc** [comment]
@darvin : Sorry for doubting your humanity, but these days you cannot be sure...

I understand now. Well, that is not the intended usage, and it might require a few changes, depending on how you plan to connect the audio / video output of the emulator.

This basic HTML does load the hosted .js/.wasm files on the fly:

```
<!DOCTYPE html>
<html>
    <body>
        <script type="module" src="https://rodrigorc.github.io/raze/raze.js"></script>
    </body>
</html>
```

There are a couple of caveats here: 
1. Do not try to load the .js directly from the `master` branch, that is intended for development and debugging. When running the _deployment_ tool, they are slightly modified and uploaded to the `gh_pages` branch. That is the one to use.
2. Trying to load a JS module directly from `raw.githubusercontent.com` fails for me because they are served as `content-type: text/plain`. Loading them from the GitHub pages directly works, however, as I did above.
3. The loaded module fails immediately, even before loading the WASM because there is no canvas in the HTML to paint on.
4. There are actually three files: `raze.js`, `pkg/raze.js` and `pkg/raze.wasm`. There is a circular dependency between the two .js because of some callbacks that are loaded directly by name. That is not the most elegant solution but, hey, it works.

Note that linking directly to the GitHub page is risky, every time I upload a new version you will be served that without warning. Maybe It would be better if you fork the repo, do the required changes and force the stability yourself. But that is up to you, of course.

**Comment by rodrigorc** [comment]
I'm closing this issue because of lack of details.
